remote_theme: pages-themes/architect@v0.2.0
title: rsans
description: A github page to show my repositories, some notes and pages or interesting third-party repositories
email: rbn.sans@gmail.com
twitter_username: rbn_sans
github_username:  rsans
linkedin_username:  rubensans
plugins:
- jekyll-remote-theme

# Build settings
markdown: kramdown
